/**
 * Property configuration — injected at build time or fetched from API.
 * In local dev, CONFIG is set here. In production, this file is
 * generated by the deploy script with real values.
 */
window.ALTUS_CONFIG = {
  propertyId: 'kentucky',
  apiBase: window.location.hostname === 'localhost'
    ? 'http://localhost:3001'
    : 'https://api.altusretreats.net/prod',
  stripePublishableKey: 'pk_test_REPLACE_ME',
  googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Playfair+Display:wght@700&display=swap',
};
