/**
 * Property configuration — injected at build time or fetched from API.
 * In local dev, CONFIG is set here. In production, this file is
 * generated by the deploy script with real values.
 */
window.ALTUS_CONFIG = {
  propertyId: 'kentucky',
  apiBase: window.location.hostname === 'localhost'
    ? 'http://localhost:3001'
    : 'https://teh1cl4b6a.execute-api.us-east-1.amazonaws.com/dev',
};
