#!/usr/bin/env bash
# deploy-frontend.sh — Build and deploy all frontends to S3 + invalidate CloudFront
# Usage: ./scripts/deploy-frontend.sh [dev|prod]
#
# Requires: aws CLI, node, npm
# AWS credentials must be configured before running.

set -euo pipefail

ENV="${1:-dev}"
STACK_NAME="altus-retreats-${ENV}"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Deploying frontends → ${STACK_NAME}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Helper: get a CloudFormation stack output value
cf_output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

# Helper: get a CloudFormation physical resource ID
cf_resource() {
  aws cloudformation describe-stack-resource \
    --stack-name "$STACK_NAME" \
    --logical-resource-id "$1" \
    --query 'StackResourceDetail.PhysicalResourceId' \
    --output text
}

echo ""
echo "▸ Fetching stack resources…"
API_URL=$(cf_output "ApiUrl")
USER_POOL_ID=$(cf_output "UserPoolId")
USER_POOL_CLIENT_ID=$(cf_output "UserPoolClientId")
FRONTEND_BUCKET=$(cf_resource "FrontendBucket")
ADMIN_BUCKET=$(cf_resource "AdminSPABucket")
PROPERTY_DIST=$(cf_resource "PropertySiteDistribution")
ADMIN_DIST=$(cf_resource "AdminSPADistribution")

echo "  API URL:         $API_URL"
echo "  Frontend bucket: $FRONTEND_BUCKET"
echo "  Admin bucket:    $ADMIN_BUCKET"

# ── Inject config into property site ───────────────────────────────────
echo ""
echo "▸ Injecting config into property site…"
cat > frontend/property-site/js/config.js << EOF
// Auto-generated by deploy-frontend.sh — do not edit manually
window.ALTUS_CONFIG = {
  propertyId: 'kentucky',
  apiBase: '${API_URL}',
  stripePublishableKey: '${STRIPE_PUBLISHABLE_KEY:-pk_live_REPLACE_ME}',
};
EOF

# ── Deploy property site to S3 ─────────────────────────────────────────
echo ""
echo "▸ Syncing property site to S3…"
aws s3 sync frontend/property-site/ "s3://${FRONTEND_BUCKET}/" \
  --delete \
  --exclude ".DS_Store" \
  --cache-control "public, max-age=3600"

# Long cache for immutable assets
aws s3 cp frontend/property-site/css/main.css "s3://${FRONTEND_BUCKET}/css/main.css" \
  --cache-control "public, max-age=31536000, immutable" \
  --content-type "text/css"

# ── Build and deploy admin SPA ─────────────────────────────────────────
echo ""
echo "▸ Building admin SPA…"
(cd frontend/admin-spa && \
  VITE_API_BASE="$API_URL" \
  VITE_USER_POOL_ID="$USER_POOL_ID" \
  VITE_USER_POOL_CLIENT_ID="$USER_POOL_CLIENT_ID" \
  npm ci --quiet && npm run build)

echo ""
echo "▸ Syncing admin SPA to S3…"
aws s3 sync frontend/admin-spa/dist/ "s3://${ADMIN_BUCKET}/" \
  --delete \
  --exclude ".DS_Store"

# index.html must never be cached (SPA entry point)
aws s3 cp frontend/admin-spa/dist/index.html "s3://${ADMIN_BUCKET}/index.html" \
  --cache-control "no-cache, no-store, must-revalidate"

# ── Deploy hub site ────────────────────────────────────────────────────
# (hub site is a single self-contained HTML file, no build step)
# Uncomment when hub site CloudFront distribution is wired up:
# HUB_BUCKET=$(cf_resource "HubSiteBucket")
# aws s3 cp frontend/hub-site/index.html "s3://${HUB_BUCKET}/index.html" --cache-control "no-cache"

# ── Invalidate CloudFront ──────────────────────────────────────────────
echo ""
echo "▸ Invalidating CloudFront caches…"

aws cloudfront create-invalidation \
  --distribution-id "$PROPERTY_DIST" \
  --paths "/*" \
  --query 'Invalidation.Id' \
  --output text | xargs -I{} echo "  Property site invalidation: {}"

aws cloudfront create-invalidation \
  --distribution-id "$ADMIN_DIST" \
  --paths "/*" \
  --query 'Invalidation.Id' \
  --output text | xargs -I{} echo "  Admin SPA invalidation: {}"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✓ Frontend deploy complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
